# auto-commit.yml のテスト用
name: Daily Commit test

on:
  # schedule:
  #   - cron: "0 0 * * *"  # 毎日0時(UTC)に実行
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # これを追加
      - name: Check GITHUB_TOKEN Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}
      - name: Update File
        run: |
          echo "$(date)" >> last_commit.txt  # 日付を更新
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add last_commit.txt
          git commit -m "Automated commit on $(date)"
          git push origin main # ブランチを指定
