name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時(UTC)に実行

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # これを追加

      - name: Update File
        run: |
          echo "$(date)" >> last_commit.txt  # 日付を更新
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add last_commit.txt
          git commit -m "Automated commit on $(date)"
          git push origin main # ブランチを指定
